spring:
  datasource:
      url: jdbc:mysql://21fc140097.iask.in:37715/mytest
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      #配置监控统计拦截的filter，去掉监控界面sql将无法统计，‘wall’用于防火墙
      filters: log4j,stat,wall
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize:
      #最大链接等待时间
      maxWait: 60000
      #打开PSCache，并且指定每个链接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql = true;druid.stat.slowSqlMillis=5000
      minldle: 1
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
#  configuration:
#    auto-mapping-behavior: full
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.huiju.cms.pr.domain

  config-location: classpath:mybatis-config.xml
  mapperLocations: classpath:mapper/**/*.xml

logging:
    level:
        ROOT: DEBUG
        com.jsjx.dorm: DEBUG

server:
    port: 8080